config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  devise_for :users
  get 'home/about'
  resources :users,only: [:show,:index,:edit,:update] do
     member do
       get :following, :followers
     end
   end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments,only: [:create,:destroy]
  end
  resources :relationships, only: [:create,:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	attachment :image
	has_many :book_comments,dependent: :destroy
	has_many :favorites,dependent: :destroy
	has_many :favorite_users, through: :favorites, source: :user
	
		def favorite?(book, user)
		book.favorites.find_by(user_id: user.id)
    end
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment,presence:true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :user_id, presence: true
  validates :book_id, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id,presence: true
  validates :followed_id,presence: true
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable
         
  has_many :favorite_book, through: :favorites, source: :book
  has_many :books, dependent: :destroy
  has_many :book_comments,dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following,through: :active_relationships,source: :followed
  has_many :followers,through: :passive_relationships,source: :follower
  attachment :profile_image, destroy: false
  validates :name, presence:true
  
  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
  
 
  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
	protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  #sign_out後のredirect先変更する。rootパスへ。rootパスはhome topを設定済み。
  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    #sign_upの際にnameのデータ操作を許。追加したカラム。
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
     book = Book.find(params[:book_id])
     comment = current_user.book_comments.new(book_comment_params)
     comment.book_id = book.id
     comment.save
     redirect_to book_path(book)
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    @comment = @book.book_comments.find_by(book_id: @book.id, id: params[:id])
    @comment.destroy
    redirect_to book_path(@book)
  end
  private
  def book_comment_params
  params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
before_action :baria_user, only: [:update]
  def show
  	@book = Book.find(params[:id])
  	@user = @book.user
  	@books =Book.all
  	@booknew =Book.new
  	@book_comment = BookComment.new
  end

  def index
    @book = Book.new
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
  	@book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end
  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end
  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title,:body,:image)
  end
  
 def baria_user
  	unless params[:id].to_i != current_user.id
  		redirect_to user_path(current_user)
  	end
   end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

 def create
    @favorite = current_user.favorites.create(book_id: params[:book_id])
    @book = Book.find(params[:book_id])
    redirect_to request.referer
 end
 def destroy
   @favorite = current_user.favorites.find_by(book_id: params[:book_id].to_i).destroy
   @book = Book.find(params[:book_id])
   redirect_to request.referer
   
 end
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :currentuser,only: [:create,:destroy]
  
  
  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html {redirect_to @user}
      format.js
  redirect_to request.referer
  end
  end
  
  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
      respond_to do |format|
      format.html {redirect_to @user}
      format.js
    redirect_to request.referer
  end
  end
  
  private
  
   def currentuser
  	unless params[:id].to_i != current_user.id
  		redirect_to user_path(current_user)
  	end
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!
	before_action :baria_user, only: [:edit,:following,:followers]
	# before_action :

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
 
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

def create
end

def following
 @title = "フォロー"
 @user = User.find(params[:id])
 @users = @user.following
 render 'following_show'
end

def followers
 @title = "Followers"
 @user = User.find(params[:id])
 @users = @user.followers
 render 'followers_show'
end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment.html.erb
<%= form_for [book, book_comment] do |f| %>
    <div class="row">
        <div class="col-sm-12">
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %><br>
        </div>
    </div>
    <%= f.submit "送信する", class: "btn btn-lg btn-base-1 btn-primary  mt-20 pull-right" %>
<% end %>

app/views/books/_comments.html.erb
<% book.book_comments.each do |book_comment| %>
<table class="table">
<td><%= attachment_image_tag(book_comment.user, :profile_image, :fill, 60, 60, fallback: "no-image-mini.jpg") %></td>
<td><a href="#" class="link-author"><%= book_comment.user.name %></a></td>
<td><span class="comment-date"><%= book_comment.created_at.strftime('%Y/%m/%d') %></span></td>
<td><div class="comment-entry"><%= book_comment.comment %></div></td>
<% if book_comment.user.id == current_user.id%>
<td><%= link_to "Destroy",book_book_comment_path(book.id,book_comment.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger" %></td>
	<% end %>
</table>
<% end %>

app/views/books/_error.html.erb
<% if book.errors.any? %>
	<h3><%= book.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>

app/views/books/_favorite.html.erb
<% if book.favorite?(book,current_user) %>
<td class="favorite_off">
    <%= link_to book_favorites_path(book_id: book.id), method: :delete,remote: true do %>
    <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %>
    <% end %>
</td>
<% else %>
<td class="favorite_on">
    <%= link_to book_favorites_path(book_id: book.id), method: :post,remote: true do%>
    <i class="far fa-heart" aria-hidden="true"></i>
    <%= book.favorites.count %>
    <% end %>
</td>
<% end %>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<!-- エラーメッセージ表示-->
<% if @book.errors.any? %>
	<h3><%= @book.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>
</div>

app/views/books/index.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'error' ,book: @book %>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					
				<div id="favorite_btn">
				 <%= render 'favorite', book: book %>
				 </div>
					
					<td><p class="comment-count">コメント数: <%= book.book_comments.count %></p></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->


	</div>
</div>
</dev>

app/views/books/show.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
	<table class="table">
		<tr><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= @user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= @user.introduction %></th>
		</tr>
</table>
<% if current_user.id == @book.user_id %>
<div class="row">
	<%= link_to '',edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %>
</div>
<% end %>

		<h2>New book</h2>
		<%= render 'books/newform' ,book:@booknew %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to @book.user   do%>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					<div id="favorite_btn">
				 <%= render 'favorite', book: @book%>
				 </div>
					<td><p class="comment-count">コメント数: <%= @book.book_comments.count %></p></td>
					<% if @book.user_id == current_user.id%>
          <!--詳細ページのユーザーのidとログインしているユーザーのidが等しい場合---->
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
			<% end %>
				</tr>
			</table>
			
			<h3>Comment</h3>
			<%= render 'comments' , book:@book %>
			<%= render 'book_comments/comment',book:@book,book_comment:@book_comment %>
	</div>
</div>
</div>

app/views/favorites/create.js.erb
$('#favorite_btn').html("<%= j(render  'books/favorite',  book: @book ) %>")

app/views/favorites/destroy.js.erb
$('#favorite_btn').html("<%= j(render  'books/favorite',  book: @book ) %>")

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f95b9e0dc0.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <body>
    <%= yield %>
    <!--ヘッダーの記述-->
    <div class="container">
      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->

    </div>
  </body>
</html>

app/views/relationships/crerate.js.erb
$("#follow_form").html("<%= escape_javascript(render 'users/unfollow') %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render 'users/follow') %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/shared/_stats.html.erb
<% user ||= current_user %>
<div class="stats">
  <td><a href="<%= following_user_path(user) %>">
    <strong id="following" class="stat">
      <%= user.following.count %>
    </strong>
    following
  </a></td>
 
  <td><a href="<%= followers_user_path(user) %>">
    <strong id="followers" class="stat">
      <%= user.followers.count %>
    </strong>
    followers
  </a></td>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build,remote:true) do |f| %>
<%= hidden_field_tag :followed_id, user.id %>
<%= f.submit "フォロー",class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless user == current_user %>
  <div id="follow_form">
  <% if current_user.following?(user) %>
    <%= render 'unfollow', user:user %>
  <% else %>
    <%= render 'follow' ,user:user%>
  <% end %>
  </div>
<% end %>

app/views/users/_profile.html.erb
<table class="table">
		<td><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></td>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
      <th><%= current_user.favorites.count %>いいね</th>
      <th>コメント数: <%= current_user.book_comments.count %></th>
    </tr>
		<tr>
			<div class="stats"><%= render 'shared/stats', user:user %></div>
		</tr>
</table>
<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
            html: { method: :delete },
            remote:true) do |f| %>
<%= f.submit "アンフォロー",class: "btn btn-danger" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
<div class="row">
<div class="col-xs-6">
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %><br>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %><br>
</div>

<div class="field">
	<%= f.label :introduction %><br>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit "Update User",class: "btn btn-primary" %>
</div>

<% end %>
</div>
</div>
</div>

app/views/users/followers_show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 offset-xs-2">
<h1>Followers</h1>
<table class="table">
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<div class="stats"><%= render 'shared/stats', user:user %></div>
			
			<td><%= render 'follow_form',user:user %></td>
			
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>
</div>

app/views/users/following_show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 offset-xs-2">
<h1>Following</h1>
		<table class="table">
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<div class="stats"><%= render 'shared/stats', user:user %></div>
			
			<td><%= render 'follow_form',user:user %></td>
			
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="row">
<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: current_user %>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>
</div>

<div class="col-xs-9">
<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<div class="stats"><%= render 'shared/stats', user:user %></div>
			
			<td><%= render 'follow_form',user:user %></td>
			
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>
</div>
<!--users一覧 -->

app/views/users/show.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">
<h2>User info</h2>
		<%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %>
<table class="table">
		<tr>
			<th>name</th>
			<th><%= @user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= @user.introduction %></th>
		</tr>
		<tr>
      <th><%= current_user.favorites.count %>いいね</th>
      <th>コメント数: <%= current_user.book_comments.count %></th>
    </tr>
    	<tr>
			<div class="stats"><%= render 'shared/stats', user:@user %></div>
		</tr>
</table>

<% if @user.id == current_user.id %>
<div class="row">
	<%= link_to '',edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %>
</div>
<% end %>
<% if @user.id !=current_user %>
	<%= render 'follow_form',user:@user ,class: "col-xs-12"%>
	<% end %>
	
<h2>New book</h2>
<%= render 'books/newform', book: @book %>
</div>
	<div class="col-xs-9">
<h2>Books</h2>
<!--books一覧 -->
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td>
				<%= link_to (book.user) do %>
				<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				<% end %>
			</td>
			<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
			<td><p class="comment-count">コメント数: <%= book.book_comments.count %></p></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>
</div>
<!--books一覧 -->

app/views/users/show_follow.html.erb
<!--フォローしているユーザーとフォロワーの両方を表示する-->
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Books:</b> <%= @user.book_comment.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            	<%= attachment_image_tag(user, :profile_image, :fill, 30, 30, fallback: "no-image-mini.jpg") %><br>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
    <% end %>
  </div>
</div>